version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # imagens do docker-compose.yml, docker-compose.ntfy.yml e docker-compose.scripts.yml, e o FROM do Dockerfile.scripts
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
