version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # images in docker-compose.yml, docker-compose.ntfy.yml and docker-compose.scripts.yml, and the FROM in Dockerfile.scripts
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
